spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/UserService?useSSL=false
    username: root
    password: Admin@123
server:
  port: 8080
  
---
spring:
  profiles: staging
  datasource:
    url: jdbc:mysql://${dbhost}:3306/${database}?useSSL=false
server:
  port: 8080
---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://${dbhost}:3306/${database}?useSSL=false
server:
  port: 8080
  
